### ISSUE TITLE
What dose "Create a deployment for namesrv, and expose namesrv service with NodePort." mean？ 

### ISSUE THREAD

**Issue by cuijxin** [huanwei/rocketmq-operator#45]
请问：tutorial.md里这句话“Create a deployment for namesrv, and expose namesrv service with NodePort.”的意思是需要在deploy/00-namesrv.yaml里加上service的定义吗？
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-namesrv
  namespace: rocketmq-operator
  labels:
    app: rocketmq-namesrv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rocketmq-namesrv
  template:
    metadata:
     labels:
       app: rocketmq-namesrv
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: namesrv
        image: rocketmqinc/rocketmq:4.3.2
        command: ["sh","mqnamesrv"]
        imagePullPolicy: Always
        ports:
          - containerPort: 9876
        volumeMounts:
          - mountPath: /home/rocketmq/logs
            name: namesrvlogs
          - mountPath: /home/rocketmq/store
            name: namesrvstore
      volumes:
      - name: namesrvlogs
        hostPath:
          path: /data/namesrv/logs
      - name: namesrvstore
        hostPath:
          path: /data/namesrv/store
      #nodeSelector:
           #rocketmq-operator: "on"
---
apiVersion: v1
kind: Service
metadata:
  name: rocketmq-namesrv
  namespace: rocketmq-operator
  labels:
    app: rocketmq-namesrv
spec:
  ports:
  - port: 9876
    protocol: TCP
    targetPort: 9876
  selector:
    app: rocketmq-namesrv
  type: NodePort
```

还有就是deploy/04-cluster-2m.yaml里的spec.nameServers参数传递的是namesrv的pod的节点IP+port，还是service的clusterIP+port？
